apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: eltcarlos/parking-front
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          env:
            - name: VITE_BACKEND_URL
              value: "http://backend-svc:3001/api"
