apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  MONGO_URI: "mongodb+srv://eltcarlosfn:1b8NqfW7BeaFYkBa@cluster0.6rygg.mongodb.net/parking?retryWrites=true&w=majority&appName=Cluster0"
  PORT: "3000"
